### PR TITLE
Ripple at the top of TimetableListItem is cut off.

### LINKED ISSUE #960: Ripple at the top of TimetableListItem is cut off.
**Idea Description**
Sorry if this is unnecessary.

Top of Ripple is cut off when tapping `TimetableListItem` used in 3 screens `BookmarkList`, `SearchList`, `TimetableList`.

Personally, I would have preferred to see Ripple up to Divider when I tapped TimetableListItem.

**Reference images and links**
|list|picture|
|---|---|
|BookmarkList||
|SearchList||
|TimetableList||

### PR DESCRIPTION
**Pull request by kosenda**
## Issue
- close #960

## Overview (Required)
- I wanted to make it clickable including padding, so I set clickable before padding and removed the original `onClick`.

## Screenshot (Optional if screenshot test is present or unrelated to UI)
Pixel6
List | Before | After
:--: | :--: | :--:
BookmarkList |  | 
SearchList |  | 
TimetableList |  |

### CODE REVIEW

**Comment by kosenda** [comment]
I changed the code as it seemed to make a difference with `checkMediumTabletLaunchShot`, but the test results were not specifically updated.
Just to be sure, I checked using AndroidStudio's Emulator and think there may be no problem.

Emulator (Medium Tablet API 28)
TimetableList
|Before|After|
|---|---|
|||

**Comment by takahirom** [comment]
I'm willing to merge this but do you want to fix this?
image

**Comment by kosenda** [comment]
@takahirom 
I think that it does not need to be modified!
Also, there are conflicts happening, so I'll fix them!

**Comment by takahirom** [comment]
Thanks! It is the ideal behavior!

**Review by takahirom — APPROVED** [review]

**Pull request merged**
