### PR TITLE
Update BookmarkTopArea Colors to Use Theme Colors

### LINKED ISSUE #277: Update BookmarkTopArea Colors to Use Theme Colors
BookmarkTopArea currently uses the hardcoded colors Color(0xFFF8FAF6) and Color(0xFFCEE9DB). We should update these colors to use our theme colors for consistency across our app and to simplify future color changes.

https://github.com/DroidKaigi/conference-app-2023/blob/main/feature/sessions/src/main/java/io/github/droidkaigi/confsched2023/sessions/component/BookmarkTopArea.kt

### PR DESCRIPTION
**Pull request by tfandkusu**
## Issue
- close #277

## Overview (Required)

I checked [Figma](https://www.figma.com/file/MbElhCEnjqnuodmvwabh9K/DroidKaigi-2023-App-UI?type=design&node-id=55032-63653&mode=design&t=PXv9x7fY3I8fwZEF-4).

### `BookmarkTopArea`'s color

- `BookmarkTopArea`'s color is `surface` color. So I used it.

### `BookmarkTopArea`'s scrolled color

- `BookmarkTopArea`'s scolled color is [surface at +2 color + 8% Primary](https://www.figma.com/file/MbElhCEnjqnuodmvwabh9K/DroidKaigi-2023-App-UI?type=design&node-id=56041-40067&mode=dev).
-  I used `MaterialTheme.colorScheme.surfaceColorAtElevation(3.dp)`

#### Reason

In the `ColorScheme.surfaceColorAtElevation` method.

```kt
val alpha = ((4.5f * ln(elevation.value + 1)) + 2f) / 100f
return surfaceTint.copy(alpha = alpha).compositeOver(surface)
```

When `elevation.value` is `3.0`, `alpha` is `0.08`.
`surfaceTint` color is same as `primary`.
In figma, `surface at +2 color + 8% Primary` is calculated by `primary`, `surface` and `8%`.
 
## Links

-

## Screenshot

Before | After
:--: | :--:
<video src="https://github.com/DroidKaigi/conference-app-2023/assets/16898831/9eebccc7-2a30-4eb9-ad77-3efbb647051b" width="300" /> | <video src="https://github.com/DroidKaigi/conference-app-2023/assets/16898831/88eb99ff-b809-459c-b868-7a55c1134671" width="300" />

### Dark Theme

https://github.com/DroidKaigi/conference-app-2023/assets/16898831/b95ed280-2789-4808-9439-effbd379a904

### CODE REVIEW

**Comment by tfandkusu** [comment]
Sorry, I forgot existing Figma.
I will check it.

**Comment by tfandkusu** [comment]
@takahirom I have question about [Surface at +2 +8% Primary](https://www.figma.com/file/MbElhCEnjqnuodmvwabh9K/DroidKaigi-2023-App-UI?type=design&node-id=56041-40067&mode=dev) in Figma.
This color is used [scrolled color of BookmarkTopArea](https://www.figma.com/file/MbElhCEnjqnuodmvwabh9K/DroidKaigi-2023-App-UI?type=design&node-id=54902-40970&mode=dev) in Figma.
I could not find method to calculate this color.
Is ` MaterialTheme.colorScheme.surfaceColorAtElevation(2.dp)` corrent ?

**Comment by takahirom** [comment]
I'm not sure. We are on the same page 😂I'll check it.

**Comment by takahirom** [comment]
Sorry, I updated the theme color please fix the conflict 🙏

**Comment by tfandkusu** [comment]
@takahirom Thanks. I fixed conflict.

**Comment by takahirom** [comment]
Thanks for investigate the ColorScheme.surfaceColorAtElevation method.
The reason diffs doesn't change is that there isn't change. So you use the right theme setting!

**Comment by takahirom** [comment]
Thanks!

**Pull request merged**
