### PR TITLE
[fix/#1237] achievements image size issue

### LINKED ISSUE #1237: Electric eel is a little bigger on Achievements screen
**Idea Description**
The title says everything

**Reference images and links**
image

### PR DESCRIPTION
**Pull request by gy6543721**
## Issue
- close #1237 

## Overview (Required)
- Fix achievements image size inconsistency issue

## Screenshot (Optional if screenshot test is present or unrelated to UI)
Before | After
:--: | :--:
截圖 2023-09-16 13 04 05 | 截圖 2023-09-16 15 58 20

### CODE REVIEW

**Comment by takahirom** [comment]
It seems that it will be big 👀 
image

**Comment by gy6543721** [comment]
> It seems that it will be big 👀 image

Fixed and updated.

**Comment by gy6543721** [comment]
@takahirom 
May I ask is there anyone reviewing this PR ?
There's no update for a long time.
Problem solved and need someone to approve for merging, thanks.

**Review by takahirom — APPROVED** [review]
Sorry for being late. looks great!

**Pull request merged**
