### PR TITLE
Implement shimmer effect as placeholder instead of "empty" string for timetable

### LINKED ISSUE #500: Implement Shimmer Effect as Placeholder Instead of "empty" String for Timetable
**Idea Description**
Currently, the DroidKaigi app displays the string "empty" as a placeholder in certain situations. To enhance the visual appeal, we should replace this with a shimmer effect.

Show a shimmer effect as a placeholder when content is loading or unavailable.

**Reference images and links**

### PR DESCRIPTION
**Pull request by sanao1006**
## Issue
- close #500 

## Overview (Required)
- Currently displaying the string "empty" while loading content, so display a shimmer effect as a placeholder to enhance visual appeal

## Links
- [dependency: compose-shimmer](https://github.com/valentinilk/compose-shimmer)

## Screenshot
Before | After
:--: | :--:
| image |image |
## Movie
https://github.com/DroidKaigi/conference-app-2023/assets/62137820/d25b1da5-6b9b-4be4-a00a-25fbdedc1d9c

### CODE REVIEW

**Comment by takahirom** [comment]
I don't know why but it looks like this PR's CI seems strange 🤔

**Comment by takahirom** [comment]
Maybe the shimmer effect prevents the test to finish?

**Comment by sanao1006** [comment]
I'll look into the cause too...

**Review by takahirom — APPROVED** [review]
Thanks for providing awesome experience!

**Pull request merged**
