### PR TITLE
[iOS] :wrench: The numerical value where cornerRadius is currently assigned is replaced by the defined Radius value.

### LINKED ISSUE #1183: [iOS] Use the defined Radius on each screen.
- Use the Typography implemented in task #1143 on each screen.

### PR DESCRIPTION
**Pull request by Corvus400**
## Issue
- close #1183 

## Overview (Required)
- The title says it all.
- I omitted the video because I simply replaced the same values...should I add them? 🤔

### CODE REVIEW

**Review by ry-itto — APPROVED** [review]
LGTM! Thanks 👍🏼

**Comment by ry-itto** [comment]
@Corvus400 
Sorry, this PR is conflicted.. Please fix this 🙇🏼

**Comment by Corvus400** [comment]
@ry-itto 
I'll fix it during lunch time at Droidkaigi 🍱.

**Comment by Corvus400** [comment]
@ry-itto 
I arrived at the venue and had extra time to resolve the code conflicts. 
Please merge when you are free. 🙏

**Pull request merged**
