### PR TITLE
Improve bookmark button accessibility

### LINKED ISSUE #462: Missing talkback explanation for Timetable/bookmark icon button
**Describe the bug**
Missing talkback explanation for Timetable/bookmark icon button

The contentDescription should have.

**To Reproduce**
1. Go to Timetable screen
2. Tap bookmark button

**Expected behavior**

When the attendees tap the bookmark button, should explains about button feature / type etc...

**Screenshots**

### PR DESCRIPTION
**Pull request by Pluu**
## Issue
- close #462

## Overview (Required)
- Use IconToggleButton instead of IconButton for the Check state.
- Added accessibility statements based on whether or not to add a bookmark.

## Links
- None

## Record

Before

https://github.com/DroidKaigi/conference-app-2023/assets/1534926/3eaa8fac-b877-41e7-b7d0-9c7172ccabbd 

After

https://github.com/DroidKaigi/conference-app-2023/assets/1534926/3be43433-92c3-4f9d-879e-ee0be39f6195

### CODE REVIEW

**Comment by takahirom** [comment]
The icon color looks changed. Looks good though. Is there any opinion about this? 👀

**Comment by Pluu** [comment]
@takahirom Oh!! My mistake.
I just realized this is different from the Figma design.
I'll make sure to expose it with the existing colors.

**Comment by Pluu** [comment]
@takahirom I used the same Color value for the IconToggleButton as in Figma.

## Figma



## Preview

**Review by takahirom — APPROVED** [review]
Looks great! Thanks

**Pull request merged**
