### PR TITLE
:recycle: Add template text for when pasting videos.

### PR DESCRIPTION
**Pull request by Corvus400**
## Issue
- none.

## Overview (Required)
- I added the template because I wanted to have before/after display when pasting videos as well.
- The video below is a sample of the display.

## Movie(PR Template sample)
Before | After
:--: | :--:
<video src="https://github.com/DroidKaigi/conference-app-2023/assets/13657682/f9a89c8f-dccd-4505-96d8-5b1b38b51616" width="300" > | <video src="https://github.com/DroidKaigi/conference-app-2023/assets/13657682/a3d6f7c9-68a8-4ed7-89c4-da9c076935df" width="300" >

### CODE REVIEW

**Comment by takahirom** [comment]
Thanks. We can easily confirm the behavior with this but I think there is a tradeoff that beginners may find challenging. 👀

**Comment by Corvus400** [comment]
I was thinking of this as an optional template for attaching images or videos.
Should I add a comment out indicating that it is not required?🙇‍♂️

**Comment by takahirom** [comment]
That would be great!

**Comment by takahirom** [comment]
I was wanting to encourage the screenshot test. So I added it as well.

**Comment by takahirom** [comment]
Thanks for bringing this to my attention!

**Pull request merged**
