### PR TITLE
Implementation fake response of "WELCOME_TALK"

### LINKED ISSUE #667: Add "Welcome Talk" session to FakeSessionsApiClient
**Idea Description**
In order to facilitate various testing scenarios, we need to add a "Welcome Talk" session to the FakeSessionsApiClient. This addition should follow the pattern established in Timetable.fake().

**Reference images and links**
For guidance on how to add the session to FakeSessionsApiClient, please refer to the following pull request: [PR #576](https://github.com/DroidKaigi/conference-app-2023/pull/576).

### PR DESCRIPTION
**Pull request by sanao1006**
## Issue
- close #667 

## Overview (Required)
- Added "Welcome Talk" session to FakeSessionsApiClient to facilitate various testing scenarios

## Concern
- Are the "startsAt" and "endsAt" times not appropriate?(https://github.com/DroidKaigi/conference-app-2023/issues/667#issuecomment-1685985567)
    > But can you use this time to see it in the screenshot tests?
startsAt":"2023-09-14T10:30:00+09:00","endsAt":"2023-09-14T11:00:00+09:00" (This is the start time of DroidKaigi)
- Should I use enum for sessionType?

### CODE REVIEW

**Comment by sanao1006** [comment]
@takahirom 

It seems that a null reference occurred on line 126 of the "io.github.droidkaigi.confsched2023.data.sessions.DefaultSessionsApiClientKt.toTimetable" method, so I investigated.
As a result, I found that it seems to refer to a category ID that does not exist👀
https://github.com/DroidKaigi/conference-app-2023/blob/8513955fbc01339dd41cdf6f333bac5040abd521/core/data/src/commonMain/kotlin/io/github/droidkaigi/confsched2023/data/sessions/DefaultSessionsApiClient.kt#L126

On second thought, the FakeSessionsApiClient only added categories with IDs 1 and 2. However, it seems that it was caused by setting sessionCategoryItemId = 182589.

https://github.com/DroidKaigi/conference-app-2023/blob/8513955fbc01339dd41cdf6f333bac5040abd521/core/data/src/commonMain/kotlin/io/github/droidkaigi/confsched2023/data/sessions/FakeSessionsApiClient.kt#L57-L75

I will fix it later and push again!

**Comment by tomoya0x00** [comment]
@sanao1006 

> Are the "startsAt" and "endsAt" times not appropriate?

IMO, it would be better to use the actual DroidKaigi2023 start date of 9/14.

> Should I use enum for sessionType?

There is no need to use enum for sessionType in SessionResponse since it is converted to enum by the below code.

https://github.com/DroidKaigi/conference-app-2023/blob/d25814d3526baa5fa93426dbb80d60e1da9f2a3a/core/data/src/commonMain/kotlin/io/github/droidkaigi/confsched2023/data/sessions/DefaultSessionsApiClient.kt#L105

**Comment by sanao1006** [comment]
https://github.com/DroidKaigi/conference-app-2023/issues/667#issuecomment-1685985567
> @sanao1006 I think you can make PR and we can comment on it. But can you use this time to see it in the screenshot tests? `startsAt":"2023-09-14T10:30:00+09:00","endsAt":"2023-09-14T11:00:00+09:00"` (This is the start time of DroidKaigi)

すみません、なぜか誤訳して勘違いしていました。この時間を使用してくださいという意味でしたよね。申し訳ないです...

**Review by takahirom — APPROVED** [review]
Looks great! Thanks for your cooperation!

**Pull request merged**
