### PR TITLE
Implement TimetableItemDetail section and UiState

### LINKED ISSUE #672: Extract TimetableItemDetailContent section and create UiState for it
**Idea Description**
The title says everything. Please refer to the link to see the implementation 

**Reference images and links**
https://github.com/DroidKaigi/conference-app-2023/pull/652/files#diff-56fac00aca9688edbb218b72743e3ef63d925bfa243b61b3d2f7b59f3debb79cR140
https://github.com/DroidKaigi/conference-app-2023#section

### PR DESCRIPTION
**Pull request by matsumo0922**
## Issue
- close #672

## Overview (Required)
- Implement `TimetableItemDetail` section
- Implement `TimetableItemDetailSectionUiState`

## Required review point
- `TimetableItem` information is also used on the Screen, there are two redundant `TimetableItems` in the `TimetableItemDetailScreenUiState`. Is this the correct implementation?

### CODE REVIEW

**Comment by takahirom** [comment]
Please fix the conflict 🙏

**Comment by matsumo0922** [comment]
Rebased!

**Comment by matsumo0922** [comment]
Hmmm, CI is failed, but I can't figure out why...
At any rate, :retry:

**Comment by matsumo0922** [comment]
I could not retry my authority...
It is timeout error so next time it will succeed.

Can someone please retry?

**Comment by takahirom** [comment]
We might have to extend time for build

**Review by takahirom — APPROVED** [review]
Looks great! Thanks for consistent code!

**Comment by takahirom** [comment]
Please fix the format 🙏

**Comment by matsumo0922** [comment]
Format seems fine.
Looking at the error, it looks like some kind of request timed out.

I don't have permission to re-run, but next one will succeed.

**Comment by takahirom** [comment]
Sorry for bothering you! Thanks!

**Pull request merged**
