### PR TITLE
:wrench: Use Annotation prepared in #523

### PR DESCRIPTION
**Pull request by Corvus400**
## Issue
- none.

## Overview (Required)
- Use Annotation prepared in #523

### CODE REVIEW

**Comment by takahirom** [comment]
I'm going to fix this. Please wait 🙏 
https://github.com/DroidKaigi/conference-app-2023/pull/605

**Comment by takahirom** [comment]
Please fix the conflict to see the preview tests!

**Comment by Corvus400** [comment]
PreviewTest now runs correctly! 🎉 
スクリーンショット 2023-08-17 17 55 30

**Comment by takahirom** [comment]
Now that we have merged solution for this, we can merge this!

**Comment by takahirom** [comment]
Thanks for making our app visible!

**Pull request merged**
