### PR TITLE
In contributors screen, navigation back button becomes transparent after scrolling

### LINKED ISSUE #827: The color of arrow to navigate up should be changed
**Idea Description**
The color of arrow to navigate up will be transparent after scrolling

**Reference images and links**
スクリーンショット 2023-08-21 21 36 23

You can remove this TODO commends in this PR
https://github.com/DroidKaigi/conference-app-2023/blob/788fb4f7f65a7aae4ee5d4773cf14bc7c33d8089/feature/contributors/src/commonMain/kotlin/io/github/droidkaigi/confsched2023/contributors/ContributorsScreen.kt#L69

### PR DESCRIPTION
**Pull request by Hachimori**
## Issue
- close #827 

## Overview (Required)
- In contributors screen, navigation back button becomes transparent after scrolling.

## Links
- 

## Movie
Before | After
:--: | :--:
<video src="https://github.com/DroidKaigi/conference-app-2023/assets/3529042/538111dc-f762-4ca0-baa4-2d11895cf275" width="300" > | <video src="https://github.com/DroidKaigi/conference-app-2023/assets/3529042/c594be0b-c366-4229-b96d-8d6145ae594c" width="300" >

### CODE REVIEW

**Comment by takahirom** [comment]
> The color of arrow to navigate up will be transparent after scrolling

I think `after scrolling` is a important part of this issue 🙇

**Comment by Hachimori** [comment]
> I think after scrolling is a important part of this issue 🙇

Sorry, I misunderstood the issue.
I'll work on fixing it.

**Comment by Hachimori** [comment]
@takahirom 

I've made following change:
- Navigation back button becomes transparent **after scrolling**.

Please kindly review again. Thank you!

**Comment by takahirom** [comment]
I'm not sure why KaigiAppTest shows invisible back button. But it looks good.
[KaigiAppTest](https://github.com/DroidKaigi/conference-app-2023/blob/companion_feature/issue827-remove-arrow-back-icon/screenshot-diff/app-android/build/outputs/roborazzi/KaigiAppTest.checkNavigateToContributorShot_compare.png)

**Comment by Hachimori** [comment]
> I'm not sure why KaigiAppTest shows invisible back button.

It should be because [this test result](https://github.com/DroidKaigi/conference-app-2023/pull/983#issuecomment-1694603270) is still showing the diff of my first implementation to remove navigation back icon.

I have checked raw roborazzi output from [the 1st test result](https://github.com/DroidKaigi/conference-app-2023/actions/runs/5989747431) and [the 2nd test result](https://github.com/DroidKaigi/conference-app-2023/actions/runs/5990117785).
- The taken screenshot can be seen from `screenshot-diff.zip` > `app-android` > `build` > `outputs` > `roborazzi` > `KaigiAppTest.checkNavigateToContributorShot_actual.png`.
- From [the 1st test result](https://github.com/DroidKaigi/conference-app-2023/actions/runs/5989747431), roborazzi takes screenshot where the back icon is removed.


- From [the 2nd test result](https://github.com/DroidKaigi/conference-app-2023/actions/runs/5990117785), there's no `KaigiAppTest.checkNavigateToContributorShot_actual.png` file, which probably means that the screenshot has no difference with existing one.
  - So, I suppose that my current implementation successfully passes screenshot testing, however, [this test result](https://github.com/DroidKaigi/conference-app-2023/pull/983#issuecomment-1694603270) was not updated.

**Comment by takahirom** [comment]
Oh I see! Thanks!

**Review by takahirom — APPROVED** [review]
Thanks for your investigation and cooperation!

**Pull request merged**
