### PR TITLE
[iOS] Update information icons on the about

### PR DESCRIPTION
**Pull request by woxtu**
## Issue
- close N/A

## Overview (Required)
- This PR updates information icons on the about

## Links
- 

## Screenshot (Optional if screenshot test is present or unrelated to UI)
Before | After
:--: | :--:
 | 

## Movie (Optional)
Before | After
:--: | :--:
<video src="" width="300" > | <video src="" width="300" >

### CODE REVIEW

**Review by tkhs0604 — COMMENTED** [review]
@woxtu 
Good catch! Thank you for finding and replacing them ✨
From the screenshots you attached, the icon sizes are changed slightly...? 👀

If possible, could you adjust these icons' size to, maybe 16x16 by adding a frame?

**Review by tkhs0604 — APPROVED** [review]
LGTM!

**Comment by woxtu** [comment]
I changed icons without thinking, but their sizes look good.

**Comment by tkhs0604** [comment]
@woxtu 
Thank you for confirming again, maybe the old one is a little larger than expected ☹️
Anyway, this is quite good catch! Let me merge it 👍

**Pull request merged**
